services:
  db:
    image: postgres:18-alpine
    container_name: node-auth-postgres-saas
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=authdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
